### PR TITLE
Added single date selection mode.

### PR DESCRIPTION
**Pull request by Ricardo-A**
Use single_date in the xml or setSingleDate(boolean)in the code. Should solve the issue#50.

### CODE REVIEW

**Comment by ArchitShah248** [comment]
@Ricardo-A : I really appreciate your work and your contribution. Kudos to that! However, It is good to have enum attribute to provide single, limited and free-range selection.

**Comment by Ricardo-A** [comment]
Hello, thank you for that and for answering. It would indeed be better to have an enum, I don't really have the time to do it though, maybe in the future. Anyway, I will leave the fork open for those who want the feature until someone makes the enum.

**Comment by Bharadhan** [comment]
> Use single_date in the xml or setSingleDate(boolean)in the code. Should fix #50.

Can anyone provide sample code for this on how to implement this

**Comment by ajayVinay** [comment]
single_date not working in xml and  there is no method setSingleDate

**Comment by kishanverma26** [comment]
> @Ricardo-A : I really appreciate your work and your contribution. Kudos to that! However, It is good to have enum attribute to provide single, limited and free-range selection.

Have you added this in latest version?

**Comment by ArchitShah248** [comment]
@kishanverma26 : It will be added in V2.0.0.

**Pull request closed without merging**
