### PR TITLE
Added feature for enabling future dates.

### PR DESCRIPTION
**Pull request by vyasenenko**

### CODE REVIEW

**Comment by ArchitShah248** [comment]
Hi @vyasenenko , I really appreciate your efforts in improvising this library. But I would like to make this API much simpler for other developers by providing the enum attributes.
1) Future
2) Past
3) Date Range

**Comment by rd7773** [comment]
Hey @ArchitShah248 ,
How to disable future dates in the current version ? Also, how to highlight today's date initially ?

**Comment by vyasenenko** [comment]
@ArchitShah248 I needed a manual choice of history dates.. So that future dates would not be active.. Added this functionality I decided to share.. Your choice to add or not

**Comment by kg6064** [comment]
unable to import library to my android application using version tag 1.1.6

**Comment by ArchitShah248** [comment]
I have added a feature to enable range of dates (past/future/range) in V1.1.6. However, V1.1.6 is yet to be published on JCentre. Cheers!!

**Pull request closed without merging**
